"""initial schema

Revision ID: 1ac50e58dbdb
Revises: 
Create Date: 2026-05-04 18:58:23.516314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac50e58dbdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('training_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MARATHON', 'TRAIL_RUNNING', 'TRIATHLON', name='sporttype'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('focus', sa.String(length=120), nullable=False),
    sa.Column('default_mode', sa.Enum('POLARIZED', 'PYRAMIDAL', 'THRESHOLD_FOCUSED', 'BASE_BUILD_PEAK', name='trainingmode'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_methods_id'), 'training_methods', ['id'], unique=False)
    op.create_index(op.f('ix_training_methods_sport'), 'training_methods', ['sport'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.Enum('MARATHON', 'TRAIL_RUNNING', 'TRIATHLON', name='sporttype'), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='athletelevel'), nullable=False),
    sa.Column('weekly_training_days', sa.Integer(), nullable=False),
    sa.Column('weekly_training_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_profiles_id'), 'athlete_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_profiles_sport'), 'athlete_profiles', ['sport'], unique=False)
    op.create_index(op.f('ix_athlete_profiles_user_id'), 'athlete_profiles', ['user_id'], unique=False)
    op.create_table('athlete_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_metric_snapshots_athlete_id'), 'athlete_metric_snapshots', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_metric_snapshots_id'), 'athlete_metric_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_metric_snapshots_measured_at'), 'athlete_metric_snapshots', ['measured_at'], unique=False)
    op.create_index(op.f('ix_athlete_metric_snapshots_metric_type'), 'athlete_metric_snapshots', ['metric_type'], unique=False)
    op.create_index(op.f('ix_athlete_metric_snapshots_provider'), 'athlete_metric_snapshots', ['provider'], unique=False)
    op.create_table('coach_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('suggested_actions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_messages_athlete_id'), 'coach_messages', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coach_messages_created_at'), 'coach_messages', ['created_at'], unique=False)
    op.create_table('device_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Enum('GARMIN', 'COROS', name='devicetype'), nullable=False),
    sa.Column('external_user_id', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=160), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('auth_status', sa.String(length=40), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_import_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_accounts_athlete_id'), 'device_accounts', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_device_accounts_id'), 'device_accounts', ['id'], unique=False)
    op.create_table('race_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MARATHON', 'TRAIL_RUNNING', 'TRIATHLON', name='sporttype'), nullable=False),
    sa.Column('distance', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_time_sec', sa.Integer(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('training_start_date', sa.Date(), nullable=True),
    sa.Column('plan_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACCEPTED', 'WARNING', 'REJECTED', name='racegoalstatus'), nullable=False),
    sa.Column('feasibility_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_goals_athlete_id'), 'race_goals', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_race_goals_id'), 'race_goals', ['id'], unique=False)
    op.create_table('training_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('weekly_training_days', sa.Integer(), nullable=False),
    sa.Column('preferred_long_run_weekday', sa.Integer(), nullable=False),
    sa.Column('unavailable_weekdays', sa.String(length=80), nullable=True),
    sa.Column('max_weekday_duration_min', sa.Integer(), nullable=True),
    sa.Column('max_weekend_duration_min', sa.Integer(), nullable=True),
    sa.Column('strength_training_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_availability_athlete_id'), 'training_availability', ['athlete_id'], unique=True)
    op.create_index(op.f('ix_training_availability_id'), 'training_availability', ['id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('race_goal_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.Enum('MARATHON', 'TRAIL_RUNNING', 'TRIATHLON', name='sporttype'), nullable=False),
    sa.Column('goal', sa.Enum('FINISH', 'IMPROVE_PACE', 'INCREASE_ENDURANCE', 'RACE_SPECIFIC', name='traininggoal'), nullable=False),
    sa.Column('mode', sa.Enum('POLARIZED', 'PYRAMIDAL', 'THRESHOLD_FOCUSED', 'BASE_BUILD_PEAK', name='trainingmode'), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('target_time_sec', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('active_skill_slug', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['race_goal_id'], ['race_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_athlete_id'), 'training_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_plans_id'), 'training_plans', ['id'], unique=False)
    op.create_index(op.f('ix_training_plans_sport'), 'training_plans', ['sport'], unique=False)
    op.create_table('plan_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'REJECTED', name='adjustmentstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('affected_workouts_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_adjustments_athlete_id'), 'plan_adjustments', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_plan_adjustments_id'), 'plan_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_plan_adjustments_plan_id'), 'plan_adjustments', ['plan_id'], unique=False)
    op.create_table('structured_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('week_index', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=40), nullable=False),
    sa.Column('workout_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('target_intensity_type', sa.String(length=40), nullable=False),
    sa.Column('target_pace_min_sec_per_km', sa.Float(), nullable=True),
    sa.Column('target_pace_max_sec_per_km', sa.Float(), nullable=True),
    sa.Column('target_hr_min', sa.Integer(), nullable=True),
    sa.Column('target_hr_max', sa.Integer(), nullable=True),
    sa.Column('rpe_min', sa.Integer(), nullable=True),
    sa.Column('rpe_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'SYNCED', 'COMPLETED', 'MISSED', name='workoutstatus'), nullable=False),
    sa.Column('adaptation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_workouts_id'), 'structured_workouts', ['id'], unique=False)
    op.create_index(op.f('ix_structured_workouts_plan_id'), 'structured_workouts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_structured_workouts_scheduled_date'), 'structured_workouts', ['scheduled_date'], unique=False)
    op.create_table('sync_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Enum('GARMIN', 'COROS', name='devicetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_tasks_id'), 'sync_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_sync_tasks_plan_id'), 'sync_tasks', ['plan_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_index', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=40), nullable=False),
    sa.Column('session_type', sa.String(length=120), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_training_sessions_plan_id'), 'training_sessions', ['plan_id'], unique=False)
    op.create_table('athlete_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_activity_id', sa.String(length=160), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('discipline', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('moving_duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('matched_workout_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['matched_workout_id'], ['structured_workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_activity_id', name='uq_activity_provider_activity_id')
    )
    op.create_index(op.f('ix_athlete_activities_athlete_id'), 'athlete_activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_activities_id'), 'athlete_activities', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_activities_matched_workout_id'), 'athlete_activities', ['matched_workout_id'], unique=False)
    op.create_index(op.f('ix_athlete_activities_provider'), 'athlete_activities', ['provider'], unique=False)
    op.create_index(op.f('ix_athlete_activities_provider_activity_id'), 'athlete_activities', ['provider_activity_id'], unique=False)
    op.create_index(op.f('ix_athlete_activities_started_at'), 'athlete_activities', ['started_at'], unique=False)
    op.create_table('provider_sync_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_workout_id', sa.String(length=160), nullable=True),
    sa.Column('provider_calendar_item_id', sa.String(length=160), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['structured_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_sync_records_athlete_id'), 'provider_sync_records', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_provider_sync_records_id'), 'provider_sync_records', ['id'], unique=False)
    op.create_index(op.f('ix_provider_sync_records_plan_id'), 'provider_sync_records', ['plan_id'], unique=False)
    op.create_index(op.f('ix_provider_sync_records_provider'), 'provider_sync_records', ['provider'], unique=False)
    op.create_table('workout_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['structured_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_feedback_workout_id'), 'workout_feedback', ['workout_id'], unique=True)
    op.create_table('workout_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=40), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_min', sa.Float(), nullable=True),
    sa.Column('target_max', sa.Float(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['structured_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_steps_id'), 'workout_steps', ['id'], unique=False)
    op.create_index(op.f('ix_workout_steps_workout_id'), 'workout_steps', ['workout_id'], unique=False)
    op.create_table('activity_laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('lap_index', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('avg_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['athlete_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_laps_activity_id'), 'activity_laps', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_laps_id'), 'activity_laps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_laps_id'), table_name='activity_laps')
    op.drop_index(op.f('ix_activity_laps_activity_id'), table_name='activity_laps')
    op.drop_table('activity_laps')
    op.drop_index(op.f('ix_workout_steps_workout_id'), table_name='workout_steps')
    op.drop_index(op.f('ix_workout_steps_id'), table_name='workout_steps')
    op.drop_table('workout_steps')
    op.drop_index(op.f('ix_workout_feedback_workout_id'), table_name='workout_feedback')
    op.drop_table('workout_feedback')
    op.drop_index(op.f('ix_provider_sync_records_provider'), table_name='provider_sync_records')
    op.drop_index(op.f('ix_provider_sync_records_plan_id'), table_name='provider_sync_records')
    op.drop_index(op.f('ix_provider_sync_records_id'), table_name='provider_sync_records')
    op.drop_index(op.f('ix_provider_sync_records_athlete_id'), table_name='provider_sync_records')
    op.drop_table('provider_sync_records')
    op.drop_index(op.f('ix_athlete_activities_started_at'), table_name='athlete_activities')
    op.drop_index(op.f('ix_athlete_activities_provider_activity_id'), table_name='athlete_activities')
    op.drop_index(op.f('ix_athlete_activities_provider'), table_name='athlete_activities')
    op.drop_index(op.f('ix_athlete_activities_matched_workout_id'), table_name='athlete_activities')
    op.drop_index(op.f('ix_athlete_activities_id'), table_name='athlete_activities')
    op.drop_index(op.f('ix_athlete_activities_athlete_id'), table_name='athlete_activities')
    op.drop_table('athlete_activities')
    op.drop_index(op.f('ix_training_sessions_plan_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_sync_tasks_plan_id'), table_name='sync_tasks')
    op.drop_index(op.f('ix_sync_tasks_id'), table_name='sync_tasks')
    op.drop_table('sync_tasks')
    op.drop_index(op.f('ix_structured_workouts_scheduled_date'), table_name='structured_workouts')
    op.drop_index(op.f('ix_structured_workouts_plan_id'), table_name='structured_workouts')
    op.drop_index(op.f('ix_structured_workouts_id'), table_name='structured_workouts')
    op.drop_table('structured_workouts')
    op.drop_index(op.f('ix_plan_adjustments_plan_id'), table_name='plan_adjustments')
    op.drop_index(op.f('ix_plan_adjustments_id'), table_name='plan_adjustments')
    op.drop_index(op.f('ix_plan_adjustments_athlete_id'), table_name='plan_adjustments')
    op.drop_table('plan_adjustments')
    op.drop_index(op.f('ix_training_plans_sport'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_training_availability_id'), table_name='training_availability')
    op.drop_index(op.f('ix_training_availability_athlete_id'), table_name='training_availability')
    op.drop_table('training_availability')
    op.drop_index(op.f('ix_race_goals_id'), table_name='race_goals')
    op.drop_index(op.f('ix_race_goals_athlete_id'), table_name='race_goals')
    op.drop_table('race_goals')
    op.drop_index(op.f('ix_device_accounts_id'), table_name='device_accounts')
    op.drop_index(op.f('ix_device_accounts_athlete_id'), table_name='device_accounts')
    op.drop_table('device_accounts')
    op.drop_index(op.f('ix_coach_messages_created_at'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_athlete_id'), table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index(op.f('ix_athlete_metric_snapshots_provider'), table_name='athlete_metric_snapshots')
    op.drop_index(op.f('ix_athlete_metric_snapshots_metric_type'), table_name='athlete_metric_snapshots')
    op.drop_index(op.f('ix_athlete_metric_snapshots_measured_at'), table_name='athlete_metric_snapshots')
    op.drop_index(op.f('ix_athlete_metric_snapshots_id'), table_name='athlete_metric_snapshots')
    op.drop_index(op.f('ix_athlete_metric_snapshots_athlete_id'), table_name='athlete_metric_snapshots')
    op.drop_table('athlete_metric_snapshots')
    op.drop_index(op.f('ix_athlete_profiles_user_id'), table_name='athlete_profiles')
    op.drop_index(op.f('ix_athlete_profiles_sport'), table_name='athlete_profiles')
    op.drop_index(op.f('ix_athlete_profiles_id'), table_name='athlete_profiles')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_methods_sport'), table_name='training_methods')
    op.drop_index(op.f('ix_training_methods_id'), table_name='training_methods')
    op.drop_table('training_methods')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
